services:
  mariadb-site:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_DATABASE=wordpress_site_db
      - MARIADB_USER=wordpress_site_user
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /home/shtf/mariadb-site:/bitnami/mariadb
    networks:
      - app-network
    restart: unless-stopped

  mariadb-store:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_DATABASE=wordpress_store_db
      - MARIADB_USER=wordpress_store_user
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /home/shtf/mariadb-store:/bitnami/mariadb
    networks:
      - app-network
    restart: unless-stopped  

  mariadb-phpbb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_DATABASE=phpbb_db
      - MARIADB_USER=phpbb_user
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /home/shtf/mariadb-phpbb:/bitnami/mariadb
    networks:
      - app-network
    restart: unless-stopped

  mariadb-osclass:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_DATABASE=osclass_db
      - MARIADB_USER=osclass_user
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /home/shtf/mariadb-osclass:/bitnami/mariadb
    networks:
      - app-network
    restart: unless-stopped

  wordpress-site:
    image: bitnami/wordpress:latest
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb-site
      - WORDPRESS_DATABASE_USER=wordpress_site_user
      - WORDPRESS_DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - WORDPRESS_DATABASE_NAME=wordpress_site_db
      - WORDPRESS_USERNAME=${ADMIN_USER}
      - WORDPRESS_PASSWORD=${ADMIN_PASSWORD}
      - WORDPRESS_EMAIL=${ADMIN_EMAIL}
    volumes:
      - /home/shtf/wordpress-site:/bitnami/wordpress
    ports:
      - "30001:8080"
    networks:
      - app-network
    restart: unless-stopped

  wordpress-store:
    image: bitnami/wordpress:latest
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb-store
      - WORDPRESS_DATABASE_USER=wordpress_store_user
      - WORDPRESS_DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - WORDPRESS_DATABASE_NAME=wordpress_store_db
      - WORDPRESS_USERNAME=${ADMIN_USER}
      - WORDPRESS_PASSWORD=${ADMIN_PASSWORD}
      - WORDPRESS_EMAIL=${ADMIN_EMAIL}
    volumes:
      - /home/shtf/wordpress-store:/bitnami/wordpress
    ports:
      - "30002:8080"
    networks:
      - app-network
    restart: unless-stopped

  phpbb:
    image: bitnami/phpbb:latest
    environment:
      - PHPBB_DATABASE_HOST=mariadb-phpbb
      - PHPBB_DATABASE_USER=phpbb_user
      - PHPBB_DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - PHPBB_DATABASE_NAME=phpbb_db
      - PHPBB_USERNAME=${ADMIN_USER}
      - PHPBB_PASSWORD=${ADMIN_PASSWORD}
      - PHPBB_EMAIL=${ADMIN_EMAIL}
    volumes:
      - /home/shtf/phpbb:/bitnami/phpbb
    ports:
      - "30003:8080"
    networks:
      - app-network
    restart: unless-stopped

  osclass:
    image: bitnami/osclass:latest
    environment:
      - OSCLASS_DATABASE_HOST=mariadb-osclass
      - OSCLASS_DATABASE_USER=osclass_user
      - OSCLASS_DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - OSCLASS_DATABASE_NAME=osclass_db
      - OSCLASS_USERNAME=${ADMIN_USER}
      - OSCLASS_PASSWORD=${ADMIN_PASSWORD}
      - OSCLASS_EMAIL=${ADMIN_EMAIL}
    volumes:
      - /home/shtf/osclass:/bitnami/osclass
    ports:
      - "30004:8080"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
